# Generated by Django 5.2.7 on 2025-11-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_era',
            field=models.CharField(default='Ancient Rome', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('player', 'item_name')},
        ),
    ]
