# Generated by Django 5.2.7 on 2025-11-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_player_current_prices_alter_player_current_era_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Anonymous Chrono-Trader', max_length=50)),
                ('time_seconds', models.IntegerField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time_seconds', 'date_recorded'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='best_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='game_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
