# Generated by Django 5.2.7 on 2025-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_leaderboardentry_player_best_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='purchase_era_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='player',
            name='current_era_index',
            field=models.IntegerField(default=0),
        ),
    ]
