# Generated by Django 5.2.8 on 2025-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_inventory_purchase_era_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='ChronoTrader', max_length=100),
        ),
    ]
