# Generated by Django 5.2.8 on 2025-11-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_player_player_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['time_seconds', 'date_recorded'], 'verbose_name_plural': 'Leaderboard Entries'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='game_app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='best_time_seconds',
            field=models.IntegerField(default=0, verbose_name='Personal Best Time (s)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_era',
            field=models.CharField(default='Stone Age', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='ChronoTrader', max_length=100, unique=True, verbose_name='Trader Identifier'),
        ),
    ]
