"""
Django settings for gamename project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""
import os
from pathlib import Path

# --- SECURITY IMPORTS ---
# Used for loading SECRETS securely from environment variables (crucial for PA)
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ----------------------------------------------------------------------
# 🔑 SECURITY CONFIGURATION (CRUCIAL FOR PRODUCTION)
# ----------------------------------------------------------------------

# 1. SECRET_KEY: Get from environment or generate a temporary one (MUST use environment in PA)
# You will set the actual SECRET_KEY as an environment variable on PythonAnywhere.
SECRET_KEY = os.environ.get('SECRET_KEY', get_random_secret_key())

# 2. DEBUG: Set to False for production
DEBUG = False

# 3. ALLOWED_HOSTS: Set to your PythonAnywhere domain (Replace 'yourusername' with your actual username)
ALLOWED_HOSTS = ['chronotrader.pythonanywhere.com',
                 'progchamp.vercel.app',
                 '*',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gamename.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gamename.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ----------------------------------------------------------------------
# 🖼️ STATIC FILES CONFIGURATION (FIXED)
# ----------------------------------------------------------------------

# 1. URL path (Correct)
STATIC_URL = 'static/'

# 2. STATIC_ROOT: Defines the destination folder for ALL collected static files. (Correct)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 3. STATICFILES_DIRS: Removed the problematic entry that pointed to STATIC_ROOT.
# We now rely on static files found in app subdirectories (e.g., game_app/static/...).
STATICFILES_DIRS = []


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
# settings.py (Add this line)
SESSION_COOKIE_DOMAIN = 'chronotrader.pythonanywhere.com'
# This is the key fix for cookies not being sent in cross-site embeds.
# It allows the browser to send the cookie when the site is embedded.
SESSION_COOKIE_SAMESITE = None
CSRF_COOKIE_SAMESITE = None

# This is REQUIRED when SAMESITE is None, as per modern browser security.
# PythonAnywhere uses HTTPS/SSL, so this should be True.
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# settings.py

# Replace 'https://your-collaborators-app.vercel.app' with the exact Vercel URL
# where your game is being embedded.
CSRF_TRUSTED_ORIGINS = [
    "https://chronotrader.pythonanywhere.com",
    "http://chronotrader.pythonanywhere.com", # Your own domain
    "https://progchamp.vercel.app", 
    "https://*.vercel.app", # Optional: Allow any Vercel subdomain
]